replicaCount: 1

ingress:
  enabled: false

image:
  repository: "danielkolodko/cat-gifs-app"
  tag: "latest"
  pullPolicy: IfNotPresent

flask:
  app: "app.py"
  env: "production"
  databaseUri: "mysql+pymysql://catuser:catpassword@mysql-service/catgifs"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
