replicaCount: 1

ingress:
  enabled: false

image:
  repository: "danielkolodko/cat-gifs-app"
  tag: "latest"
  pullPolicy: IfNotPresent

flask:
  app: "app.py"
  env: "production"
  databaseUri: "mysql+pymysql://catuser:catpassword@mysql-service/catgifs"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

prometheusStack:
  prometheusOperator:
  extraArgs:
    - "--log.level=debug"  # if you want more detail
  enabled: true
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.example.com
    adminPassword: "MySecretPassword"

standaloneGrafana:
  enabled: false
