apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cats.fullname" . }}-config
data:
  FLASK_APP: {{ .Values.configmap.FLASK_APP | quote }}
  FLASK_ENV: {{ .Values.configmap.FLASK_ENV | quote }}
