apiVersion: v1
kind: Service
metadata:
  name: {{ include "cats.fullname" . }}-flask
spec:
  selector:
    app: {{ include "cats.name" . }}-flask
  ports:
    - protocol: TCP
      port: {{ .Values.flask.service.externalPort }}
      targetPort: {{ .Values.flask.servicePort }}
  type: {{ .Values.flask.service.type }}
