{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cats.fullname" . }}-ingress
  labels:
    {{- include "cats.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-flask" (include "cats.fullname" $) }}
            port:
              number: {{ $.Values.flask.service.externalPort }}
      {{- end }}
  {{- end }}
{{- end }}
