apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cats.fullname" . }}-mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.secret.rootPassword | quote }}
  mysql-database: {{ .Values.mysql.secret.database | quote }}
  mysql-user: {{ .Values.mysql.secret.user | quote }}
  mysql-password: {{ .Values.mysql.secret.password | quote }}
