apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cats.fullname" . }}-mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cats.name" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "cats.name" . }}-mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "cats.fullname" . }}-mysql-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "cats.fullname" . }}-mysql-secret
                key: mysql-database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "cats.fullname" . }}-mysql-secret
                key: mysql-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "cats.fullname" . }}-mysql-secret
                key: mysql-password
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "cats.fullname" . }}-mysql-pvc
